-- SWC_RemoveData
-- Author: Sidney Alcantara
-- DateCreated: 4/13/2017 1:00:56 PM
--------------------------------------------------------------

-- Delete Technologies
DELETE FROM Types
	WHERE Kind = 'KIND_TECH'
	AND Type NOT IN (
		'TECH_POTTERY',
		'TECH_ANIMAL_HUSBANDRY',
		'TECH_MINING',
		'TECH_SAILING',
		'TECH_IRRIGATION',
		'TECH_MASONRY',
		'TECH_BRONZE_WORKING',
		'TECH_THE_WHEEL',
		'TECH_SHIPBUILDING',
		'TECH_CARTOGRAPHY'
	);

-- Delete Victories
DELETE FROM Types
	WHERE Kind = 'KIND_VICTORY'
	AND Type IN (
		'VICTORY_CULTURE',
		'VICTORY_RELIGIOUS',
		'VICTORY_TECHNOLOGY'
	);

-- Delete Units
DELETE FROM Types
	WHERE Kind = 'KIND_UNIT'
	AND Type NOT IN (
		'UNIT_SETTLER',
		'UNIT_BUILDER',
		'UNIT_SCOUT',
		'UNIT_TRADER',
		'UNIT_GREAT_ENGINEER',
		'UNIT_GREAT_MERCHANT',
		'UNIT_GREAT_PROPHET',
		'UNIT_GREAT_SCIENTIST',
		'UNIT_GREAT_WRITER',
		'UNIT_GREAT_ARTIST',
		'UNIT_GREAT_MUSICIAN'
	);

-- Delete Wonders
DELETE FROM Buildings
	WHERE IsWonder = 1;

-- Delete buildings from deleted districts
DELETE FROM Buildings
	WHERE PrereqDistrict IN (
		'DISTRICT_AERODROME',
		'DISTRICT_ENCAMPMENT',
		'DISTRICT_SPACEPORT'
	);

-- Delete Districts
DELETE FROM Types
	WHERE Kind = 'KIND_DISTRICT'
	AND Type IN (
		'DISTRICT_AERODROME',
		'DISTRICT_ENCAMPMENT',
		'DISTRICT_SPACEPORT'
	);

-- Delete defensive buildings
DELETE FROM Types
	WHERE Type IN (
		'BUILDING_WALLS',
		'BUILDING_CASTLE',
		'BUILDING_STAR_FORT'
	);

-- Delete Projects
DELETE FROM Types
	WHERE Kind = 'KIND_PROJECT'
	AND Type IN (
		'PROJECT_LAUNCH_EARTH_SATELLITE',
		'PROJECT_LAUNCH_MOON_LANDING',
		'PROJECT_LAUNCH_MARS_REACTOR',
		'PROJECT_LAUNCH_MARS_HABITATION',
		'PROJECT_LAUNCH_MARS_HYDROPONICS',
		'PROJECT_MANHATTAN_PROJECT',
		'PROJECT_OPERATION_IVY',
		'PROJECT_BUILD_NUCLEAR_DEVICE',
		'PROJECT_BUILD_THERMONUCLEAR_DEVICE',
		'PROJECT_ENHANCE_DISTRICT_ENCAMPMENT'
	);

-- Delete military Great People
DELETE FROM Types
	WHERE Kind = 'KIND_GREAT_PERSON_CLASS'
	AND Type IN (
		'GREAT_PERSON_CLASS_GENERAL',
		'GREAT_PERSON_CLASS_ADMIRAL'
	);